### ISSUE TITLE
Add a mac local indexer based on the new updates

### ISSUE THREAD

**Issue by hadisinaee** [ubc-systopia/Indaleko#2]
We should add a Mac local indexer which indexes the files on a Mac book. Based on the available indexers in this repo: 

- `IndalekoIndexer.py` is the base class for all indexers
- `IndalekoWindowsLocalIndexer.py` is an indexer for Windows machines. 

I need #1 as a prereq.

**Comment by fsgeek** [comment]
The Windows and Linux indexers previously were very similar.  With the IndalekoIndexer base class, it should be fairly straight-forward to build the indexer, though this would be easier if the Linux indexer is updated and use that as a base.  See #4
